library(ggplot2)

train <- read.csv("~/Documents/Studie/challenges/kaggle-twente/train.csv")

train.df <- data.frame(train)
train.clean = data.frame()
train.clean = train.df[,c(1,2,3,4,5,6,7,8,9,11)]

random = randomForest(as.factor(survived) ~ trainingset$sex + trainingset$sibsp + trainingset$parch + trainingset$fare + as.factor(trainingset$embarked), trainingset)

ggplot(train.clean, aes(x=sex, y=fare))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=age))+geom_point(aes(colour=factor(survived), alpha=0.5)) 
ggplot(train.clean, aes(x=sex, y=sibsp))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=parch))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=parch))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=pclass))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sex, y=fare))+geom_point(aes(colour=factor(survived)), alpha=0.5)
ggplot(train.clean, aes(x=sex, y=fare))+geom_point(aes(colour=factor(survived)), alpha=0.5)
ggplot(train.clean, aes(x=sex, y=fare))+geom_point(aes(colour=factor(survived), , alpha=0.5))
ggplot(train.clean, aes(x=sex, y=age))+geom_point(aes(colour=factor(survived), , alpha=0.5))
ggplot(train.clean, aes(x=pclass, y=age))+geom_point(aes(colour=factor(survived), , alpha=0.5))
ggplot(train.clean, aes(x=pclass, y=sibsp))+geom_point(aes(colour=factor(survived), , alpha=0.5))
ggplot(train.clean, aes(x=pclass, y=parch))+geom_point(aes(colour=factor(survived), , alpha=0.5))
ggplot(train.clean, aes(x=pclass, y=fare))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=pclass, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=age, y=sibsp))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=age, y=parch))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=age, y=fare))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=age, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sibsp, y=parch))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sibsp, y=fare))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sibsp, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=sibsp, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=parch, y=fare))+geom_point(aes(colour=factor(survived), alpha=0.5)) 
ggplot(train.clean, aes(x=parch, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))
ggplot(train.clean, aes(x=fare, y=embarked))+geom_point(aes(colour=factor(survived), alpha=0.5))